# Generated by Django 4.2 on 2023-08-14 07:32

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.upload_image)),
            ],
        ),
    ]
