# Generated by Django 4.2 on 2023-08-22 17:20

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='image',
            field=models.ImageField(blank=True, default='imgs/default.png', null=True, upload_to=home.models.upload_image),
        ),
    ]
