# Generated by Django 4.2 on 2023-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='blog',
            name='cateogry',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
