# Generated by Django 4.2 on 2023-09-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_blog_cateogry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cateogry',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Blog Category'),
        ),
    ]
