# Generated by Django 4.2 on 2023-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_comment_user_comment_email_comment_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Blog Title'),
        ),
    ]
