# Generated by Django 4.2 on 2023-09-09 11:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=2, upload_to=blog.models.image_upload),
            preserve_default=False,
        ),
    ]
