# Generated by Django 4.2 on 2023-09-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='comments/'),
        ),
    ]
